"""add primary key

Revision ID: e6e6db73917a
Revises: 8bc1bfea8ed0
Create Date: 2020-07-18 22:35:40.642367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e6db73917a'
down_revision = '8bc1bfea8ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
